#!/usr/bin/env bash
# Prepare an ANX asset IPC host: secrets, database.yaml, Grafana/Prometheus provisioning, init probes.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
  else
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

set_env_if_empty() {
  local key="$1"
  local val="$2"
  if grep -qE "^${key}=$" .env 2>/dev/null || ! grep -qE "^${key}=" .env 2>/dev/null; then
    if grep -qE "^${key}=" .env 2>/dev/null; then
      sed -i "s|^${key}=.*|${key}=${val}|" .env
    else
      echo "${key}=${val}" >> .env
    fi
    echo "  generated ${key}"
  elif grep -qE "^${key}=.+" .env 2>/dev/null; then
    echo "  kept existing ${key}"
  fi
}

echo "==> ANX asset IPC prepare"

if [[ ! -f .env ]]; then
  cp .env.example .env
  echo "  created .env from .env.example"
else
  echo "  using existing .env"
fi

if [[ ! -f .env.inference ]]; then
  cp .env.inference.example .env.inference
  echo "  created .env.inference from example"
fi

echo "==> Secrets (empty values only)"
set_env_if_empty POSTGRES_PASSWORD "$(gen_secret)"
set_env_if_empty MONGO_ROOT_PASSWORD "$(gen_secret)"
set_env_if_empty REDIS_PASSWORD "$(gen_secret)"
set_env_if_empty GRAFANA_ADMIN_PASSWORD "$(gen_secret)"

# Keep Grafana GF_* in sync with GRAFANA_* when GF is empty
# shellcheck disable=SC1091
set -a
# shellcheck source=/dev/null
source .env
set +a

if [[ -z "${GF_SECURITY_ADMIN_PASSWORD:-}" && -n "${GRAFANA_ADMIN_PASSWORD:-}" ]]; then
  set_env_if_empty GF_SECURITY_ADMIN_PASSWORD "$GRAFANA_ADMIN_PASSWORD"
fi
if [[ -z "${GF_SECURITY_ADMIN_USER:-}" ]]; then
  set_env_if_empty GF_SECURITY_ADMIN_USER "${GRAFANA_ADMIN_USER:-admin}"
fi

# Fail if critical secrets still empty after generation
# shellcheck disable=SC1091
set -a
# shellcheck source=/dev/null
source .env
set +a

missing=0
for k in POSTGRES_PASSWORD MONGO_ROOT_PASSWORD REDIS_PASSWORD GRAFANA_ADMIN_PASSWORD; do
  eval "v=\${$k:-}"
  if [[ -z "$v" ]]; then
    echo "ERROR: $k is still empty" >&2
    missing=1
  fi
done
if [[ "$missing" -ne 0 ]]; then
  exit 1
fi

PROFILES="${COMPOSE_PROFILES:-}"
has_profile() {
  echo ",${PROFILES}," | grep -q ",$1,"
}

echo "==> data/config/database.yaml (enabled flags match COMPOSE_PROFILES)"
mkdir -p data/config data/certs data/protocol_mappings data/grafana/provisioning/datasources \
  data/grafana/provisioning/dashboards data/grafana/dashboards data/prometheus data/mqtt

# Persistent service data under ./volumes (bind mounts — not Docker named volumes)
mkdir -p \
  volumes/victoriametrics \
  volumes/postgres \
  volumes/mongodb/data \
  volumes/mongodb/config \
  volumes/redis \
  volumes/grafana \
  volumes/prometheus \
  volumes/mqtt/data \
  volumes/mqtt/log \
  volumes/nodered \
  volumes/loki
echo "  ensured volumes/{victoriametrics,postgres,mongodb,redis,grafana,prometheus,mqtt,nodered,loki}"

REG_DB=false
has_profile registry-db && REG_DB=true

cat > data/config/database.yaml <<EOF
# Generated by prepare.sh — do not hand-edit unless you know the profile set.
database:
  instances:
    - name: victoriametrics-primary
      type: victoriametrics
      enabled: true
      hosts:
        - host: victoriametrics
          port: 8428
      connectionMode: round_robin
      victoriametrics:
        url: http://victoriametrics:8428
    - name: postgresql-primary
      type: postgresql
      enabled: ${REG_DB}
      hosts:
        - host: postgres
          port: 5432
          username: ${POSTGRES_USER:-postgres}
          password: "\${POSTGRES_PASSWORD}"
          database: ${POSTGRES_DATABASE:-anx_assets}
      connectionMode: round_robin
      postgresql:
        url: postgresql://${POSTGRES_USER:-postgres}:\${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DATABASE:-anx_assets}
    - name: mongodb-primary
      type: mongodb
      enabled: ${REG_DB}
      hosts:
        - host: mongodb
          port: 27017
          username: ${MONGO_ROOT_USERNAME:-admin}
          password: "\${MONGO_ROOT_PASSWORD}"
          database: ${MONGO_DATABASE:-anx-asset}
      connectionMode: round_robin
      mongodb:
        authSource: admin
    - name: redis-primary
      type: redis
      enabled: ${REG_DB}
      hosts:
        - host: redis
          port: 6379
          password: "\${REDIS_PASSWORD}"
      connectionMode: round_robin
      redis:
        db: 0
        keyPrefix: anx:
EOF
echo "  wrote data/config/database.yaml (registry-db=${REG_DB})"

if [[ ! -f data/config/general.yml ]]; then
  cat > data/config/general.yml <<EOF
mode: single_asset
single_asset_dir: ${SINGLE_ASSET_DIR:-asset-local}
server:
  host: "0.0.0.0"
  port: ${SERVER_PORT:-8080}
  internal_port: ${INTERNAL_PORT:-8081}
  grpc_port: ${GRPC_PORT:-50051}
  websocket_port: ${WEBSOCKET_PORT:-8082}
victoriametrics:
  url: ${VICTORIAMETRICS_URL:-http://victoriametrics:8428}
  buffer_size: 10000
  flush_interval_secs: 10
prometheus:
  enabled: true
  port: 9090
frontend:
  admin_username: admin
  admin_password: admin
  port: 3000
EOF
  echo "  wrote data/config/general.yml (default; import-asset.sh may overwrite)"
fi

echo "==> Prometheus scrape config"
# Internal API serves /metrics on INTERNAL_PORT (default 8081), not 9090.
cat > data/prometheus/prometheus.yml <<EOF
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: anx-assets-node
    metrics_path: /metrics
    static_configs:
      - targets: ['anx-assets-node:${INTERNAL_PORT:-8081}']

  - job_name: victoriametrics
    static_configs:
      - targets: ['victoriametrics:8428']
EOF

echo "==> Grafana provisioning"
mkdir -p data/grafana/provisioning/datasources data/grafana/provisioning/dashboards data/grafana/dashboards

DS_FILE=data/grafana/provisioning/datasources/anx-stack.yml
{
  echo 'apiVersion: 1'
  echo 'datasources:'
  echo '  - name: VictoriaMetrics'
  echo '    type: prometheus'
  echo '    access: proxy'
  echo '    url: http://victoriametrics:8428'
  echo '    isDefault: true'
  echo '    jsonData:'
  echo '      httpMethod: POST'
  echo '  - name: Prometheus'
  echo '    type: prometheus'
  echo '    access: proxy'
  echo '    url: http://prometheus:9090'
  echo '    isDefault: false'
  echo '    jsonData:'
  echo '      httpMethod: POST'
  if has_profile registry-db; then
    echo '  - name: Postgres'
    echo '    type: postgres'
    echo '    access: proxy'
    echo "    url: postgres:5432"
    echo "    user: ${POSTGRES_USER:-postgres}"
    echo '    secureJsonData:'
    echo "      password: ${POSTGRES_PASSWORD}"
    echo '    jsonData:'
    echo "      database: ${POSTGRES_DATABASE:-anx_assets}"
    echo '      sslmode: disable'
    echo '      postgresVersion: 1600'
  fi
  if has_profile logs; then
    echo '  - name: Loki'
    echo '    type: loki'
    echo '    access: proxy'
    echo '    url: http://loki:3100'
    echo '    isDefault: false'
  fi
} > "$DS_FILE"

cat > data/grafana/provisioning/dashboards/anx.yml <<'EOF'
apiVersion: 1
providers:
  - name: ANX
    orgId: 1
    folder: ANX
    type: file
    disableDeletion: false
    updateIntervalSeconds: 30
    options:
      path: /var/lib/grafana/dashboards
EOF

# Dashboard JSON (node gauges + VictoriaMetrics up)
cat > data/grafana/dashboards/anx-asset-node-runtime.json <<'EOF'
{
  "annotations": { "list": [] },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "panels": [
    {
      "datasource": { "type": "prometheus", "uid": "" },
      "fieldConfig": { "defaults": { "unit": "short" }, "overrides": [] },
      "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
      "id": 1,
      "targets": [
        {
          "expr": "anx_assets_total",
          "legendFormat": "assets",
          "refId": "A"
        }
      ],
      "title": "Assets total",
      "type": "stat"
    },
    {
      "datasource": { "type": "prometheus", "uid": "" },
      "fieldConfig": { "defaults": { "unit": "short" }, "overrides": [] },
      "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
      "id": 2,
      "targets": [
        {
          "expr": "anx_metrics_buffer_size",
          "legendFormat": "buffer",
          "refId": "A"
        }
      ],
      "title": "Metrics buffer size",
      "type": "stat"
    },
    {
      "datasource": { "type": "prometheus", "uid": "" },
      "fieldConfig": { "defaults": { "unit": "short" }, "overrides": [] },
      "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
      "id": 3,
      "targets": [
        {
          "expr": "anx_metrics_storage_flush_errors_total",
          "legendFormat": "flush errors",
          "refId": "A"
        }
      ],
      "title": "Flush errors",
      "type": "stat"
    },
    {
      "datasource": { "type": "prometheus", "uid": "" },
      "fieldConfig": { "defaults": { "unit": "bytes" }, "overrides": [] },
      "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
      "id": 4,
      "targets": [
        {
          "expr": "anx_metrics_memory_bytes",
          "legendFormat": "memory",
          "refId": "A"
        }
      ],
      "title": "Metrics memory",
      "type": "stat"
    },
    {
      "datasource": { "type": "prometheus", "uid": "" },
      "fieldConfig": { "defaults": {}, "overrides": [] },
      "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
      "id": 5,
      "targets": [
        {
          "expr": "anx_metrics_storage_writes_total",
          "legendFormat": "writes",
          "refId": "A"
        },
        {
          "expr": "anx_metrics_storage_flushes_total",
          "legendFormat": "flushes",
          "refId": "B"
        }
      ],
      "title": "Storage writes / flushes",
      "type": "timeseries"
    }
  ],
  "schemaVersion": 39,
  "tags": ["anx", "asset-node"],
  "templating": { "list": [] },
  "time": { "from": "now-1h", "to": "now" },
  "timezone": "browser",
  "title": "ANX asset-node runtime",
  "uid": "anx-asset-node-runtime",
  "version": 1
}
EOF

cat > data/grafana/dashboards/anx-victoriametrics.json <<'EOF'
{
  "annotations": { "list": [] },
  "editable": true,
  "id": null,
  "links": [],
  "panels": [
    {
      "datasource": { "type": "prometheus", "uid": "" },
      "fieldConfig": { "defaults": {}, "overrides": [] },
      "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
      "id": 1,
      "targets": [
        {
          "expr": "up{job=\"victoriametrics\"}",
          "legendFormat": "VM up",
          "refId": "A"
        }
      ],
      "title": "VictoriaMetrics up",
      "type": "stat"
    },
    {
      "datasource": { "type": "prometheus", "uid": "" },
      "fieldConfig": { "defaults": {}, "overrides": [] },
      "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
      "id": 2,
      "targets": [
        {
          "expr": "up{job=\"anx-assets-node\"}",
          "legendFormat": "node up",
          "refId": "A"
        }
      ],
      "title": "anx-assets-node scrape up",
      "type": "stat"
    },
    {
      "datasource": { "type": "prometheus", "uid": "" },
      "fieldConfig": { "defaults": {}, "overrides": [] },
      "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
      "id": 3,
      "targets": [
        {
          "expr": "up{job=\"node-exporter\"}",
          "legendFormat": "host",
          "refId": "A"
        }
      ],
      "title": "Node exporter up",
      "type": "stat"
    }
  ],
  "schemaVersion": 39,
  "tags": ["anx", "victoriametrics"],
  "time": { "from": "now-1h", "to": "now" },
  "timezone": "browser",
  "title": "ANX VictoriaMetrics / scrape health",
  "uid": "anx-vm-health",
  "version": 1
}
EOF

echo "==> Init readiness probes"
USB_ROOT="${ANX_USB_ASSET_INIT_ROOT:-/media/usb}"
echo "  USB watch root (host): ${USB_ROOT}"
if [[ -d "$USB_ROOT" ]]; then
  echo "    OK — directory exists (place anx-asset-init-<assetId>/ or .zip at the root)"
else
  echo "    WARN — directory missing; compose create_host_path will create an empty bind. Mount a real USB stick for USB provisioning."
fi

if [[ -e /sys/class/bluetooth/hci0 ]]; then
  echo "  BLE hci0: present"
else
  echo "  BLE hci0: absent — ANX app discovery over Bluetooth will not work; use USB or manual import"
fi

if systemctl is-active --quiet bluetooth 2>/dev/null || pgrep -x bluetoothd >/dev/null 2>&1; then
  echo "  bluetoothd: running (host must stay up for container D-Bus BLE)"
else
  echo "  bluetoothd: not detected — start host bluetoothd before BLE provisioning"
fi

REG="data/config/region-registration.yaml"
if [[ -f "$REG" ]]; then
  echo "  Manual/config: region-registration.yaml present"
else
  echo "  Manual/config: awaiting region-registration.yaml (drop file, USB stick, BLE app, or ./import-asset.sh <portal.zip>)"
fi

echo ""
echo "Next:"
echo "  docker compose up -d"
echo "  # Manual ZIP:  ./import-asset.sh /path/to/portal-setup.zip && docker compose up -d"
echo "  # USB:         start stack, then put anx-asset-init-<id> on USB at ${USB_ROOT}"
echo "  # BLE:         start stack with bluetoothd + hci0; pair ANX-NEW in the ANX app"
echo "  # Inference:   docker compose -f docker-compose.yml -f docker-compose.inference.yml --profile inference up -d"
echo "Done."
